# distributed training
nodes: 1
gpus: 8
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "0,1,2,3,4,5,6,7"

# Paths
data_root: "/mnt/zhen_chen/pyramid_features"
csv_path: "./aiec_info.csv"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "AIEC"
feature_dim: 1024
KFold: 5
num_levels: 3
downsample_factor: 4

# Model options
backbone: "Experts"
n_experts: 8
dropout: 0.25
activation: "gelu"
num_layers: 8
num_heads: 4
d_model: 512
agg: 'attn'
pretrained: ""
rate: 100

# training options
seed: 42
batch_size: 1
epochs: 250
fold: 0

# optimizer options
opt: "adamw"
ema_decay: 0.999
lr: 1.0e-3
scheduler: True
weight_decay: 0.01
warmup_epochs: 10
