# distributed training
nodes: 1
gpus: 2
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "6,7"

# Paths
data_root: "/mnt/zhen_chen/featuresx20_256"
csv_path: "./aiec_info.csv"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "AIEC"
feature_dim: 1024
KFold: 5

# Model options
backbone: "Mamba"
dropout: 0.25
activation: "gelu"
num_layers: 2
num_heads: 4
d_model: 256
agg: 'avg'
pretrained: ""

# training options
seed: 42
batch_size: 1
epochs: 200
fold: 0

# optimizer options
opt: "adamw"
ema_decay: 0.999
lr: 2.0e-4
weight_decay: 0.01
warmup_epochs: 10
