# distributed training
nodes: 1
gpus: 8
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "0,1,2,3,4,5,6,7"

# Paths
data_root: "/mnt/zhen_chen/featuresx20_256"
csv_path: "./aiec_info.csv"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "AIEC"
feature_dim: 1024
KFold: 5

# Model options
backbone: "ViT"
dropout: 0.25
activation: "gelu"
num_layers: 10
d_model: 512
agg: 'attention'
pretrained: "WinKawaks/vit-tiny-patch16-224"

# training options
seed: 42
batch_size: 1
epochs: 200
fold: 0

# optimizer options
opt: "adamw"
ema_decay: 0.999
lr: 2.0e-4
weight_decay: 0.01
warmup_epochs: 10
