# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "0,1,2,3"

# Paths
data_root: "/mnt/zhen_chen/features_TongJi_DTFD_x20_down_2_4"
csv_path: "./TongJi_AIEC.csv"
# train_csv: "./TongJi_Training_Samples.csv"
# test_csv: "./TongJi_Testing_Samples.csv"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "AIEC"
feature_dim: 1024
num_levels: 3
lowest_level: 0
downsample_factor: [2, 4]
tree_dropout: [0.1, 0.08, 0.05]
visible_levels: [0, 1, 2]

# Model options
backbone: "MambaAgents"
n_experts: 8
dropout: 0.5
activation: "relu"
num_layers: 2
num_heads: 8
d_model: 512
d_state: 32
KFold: 10
agg: 'avg'
pretrained: ""

# training options
seed: 0
batch_size: 2
epochs: 200
fold: 0

# optimizer options
opt: "adamw"
lr: 2.0e-4
scheduler: True
weight_decay: 0.01
warmup_epochs: 15
lambda_xsam: 0
lambda_xview: 0
lambda_cls: 0
