# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 0
visible_gpus: "4,5,6,7"

# Paths
data_root: "/data1/public/Li/features_TongJi_DTFD_x20_down_2_4"
train_csv_path: "./splits/AIEC_Slides_Training.xlsx"
test_csv_path: "./splits/AIEC_Slides_Testing.xlsx"
wsi_csv_path: "./splits/AIEC_Slides_Phenotypes.xlsx"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "AIEC"
feature_dim: 1024
num_levels: 3
lowest_level: 0
downsample_factor: "2, 4"
tree_dropout: "0.08, 0.04, 0.01"
visible_levels: [0, 1, 2, 3]
task: "subtyping"
kfold: 5

# Model options
backbone: "TreeMamba"
n_views: 8
dropout: 0.4
n_layers: 1
d_model: 512
d_state: 32
fix_agent: 1

# training options
seed: 2
batch_size: 3
epochs: 400
random_layer: 0.3
surv_loss: 'ce'

# optimizer options
optimizer: "AdamW"
lr: 5.0e-5
scheduler: True
weight_decay: 1.0
warmup_epochs: 20
lambda_xview: 0.05
lambda_cls: 0.0
