# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "0,1,2,3"

# Paths
data_root: "/mnt/zhen_chen/features_AIEC"
csv_path: "./aiec_info.csv"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "AIEC"
feature_dim: 1024
KFold: 5
num_levels: 3
lowest_level: 0
downsample_factor: 2
tree_dropout: [0.05, 0.1, 0.3]

# Model options
backbone: "Experts"
n_experts: 8
dropout: 0.5
activation: "gelu"
num_layers: 2
num_heads: 8
d_model: 256
d_state: 8
agg: 'cls_token'
pretrained: ""

# training options
seed: 42
batch_size: 1
epochs: 200
fold: 0

# optimizer options
opt: "adamw"
lr: 2.0e-4
scheduler: True
weight_decay: 0.05
warmup_epochs: 10
lambda_xsam: 0
lambda_xview: 0
lambda_cls: 1.0
