# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "0,1,2,3"

# Paths
data_root: "/mnt/zhen_chen/features_TongJi_DTFD_x20_down_2_4"
csv_path: "TongJi_AIEC_Aug.csv"
train_csv: ""
test_csv: ""
checkpoints: "./checkpoints"

# Dataset Options
dataset: "AIEC"
feature_dim: 1024
num_levels: 3
lowest_level: 0
downsample_factor: "2, 4"
tree_dropout: "0.08, 0.04, 0.01"
visible_levels: [0, 1, 2, 3]

# Model options
backbone: "TreeMamba"
n_experts: 8
dropout: 0.4
depth: 1
activation: "relu"
num_layers: 1
num_heads: 8
d_model: 512
d_state: 32
KFold: 10
agg: 'avg'
fix_agent: 1
pretrained: ""

# training options
seed: 0
batch_size: 2
epochs: 200
fold: 0
random_layer: 0.5

# optimizer options
opt: "adamw"
lr: 2.0e-4
beta1: 0.9
beta2: 0.98
scheduler: True
weight_decay: 0.01
warmup_epochs: 15
lambda_xview: 0.5

