# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "4,5,6,7"

# Paths
data_root: "/data1/public/Li/features_TongJi_DTFD_x20_down_2_4"
overall_csv_path: "./splits/AIEC_Phenotypes_Aug_NoDuplicates.xlsx"
train_csv: "" # ./splits/AIEC_Slides_Training.xlsx
test_csv: "" # ./splits/AIEC_Slides_Testing.xlsx
checkpoints: "./checkpoints"
results: "./results"

# Dataset Options
dataset: "AIEC"
feature_dim: 1024
num_levels: 3
lowest_level: 0
downsample_factor: "2, 4"
tree_dropout: "0.3, 0.2, 0.1"
visible_levels: [0, 1, 2, 3]

# Model options
backbone: "TreeMamba"
n_experts: 8
dropout: 0.3
depth: 1
activation: "relu"
num_layers: 1
num_heads: 8
d_model: 512
d_state: 32
KFold: 5
agg: 'avg'
fix_agent: 1
pretrained: ""

# training options
seed: 2
batch_size: 1
epochs: 500
fold: 0
random_layer: 0.1
task: 'grade'

# optimizer options
opt: "adamw"
lr: 2.0e-5
beta1: 0.9
beta2: 0.999
scheduler: False
weight_decay: 1.0
warmup_epochs: 30
lambda_xview: 0.1
accumulation_steps: 1

