# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "0,1,4,6"

# Paths
data_root: "/data1/public/Li/features_TongJi_DTFD_x20_down_2_4"
wsi_csv_path: "./AIEC_Slides_Phenotypes.xlsx"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "AIEC"
feature_dim: 1024
num_levels: 3
lowest_level: 0
downsample_factor: "2, 4"
tree_dropout: "0.08, 0.04, 0.01"
visible_levels: [0, 1, 2, 3]
task: "subtyping"
kfold: 5

# Model options
backbone: "PathAgents"
n_views: 4
dropout: 0.4
depth: 1
n_layers: 2
d_model: 512
d_state: 32
fix_agent: 1

# training options
seed: 0
batch_size: 2
epochs: 50
random_layer: 0.3
surv_loss: 'ce'

# optimizer options
optimizer: "Adam"
lr: 2.0e-4
scheduler: True
weight_decay: 0.01
warmup_epochs: 5
lambda_xview: 0.5

