# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "0,1,2,3"

# Paths
data_root: "/mnt/zhen_chen/features_CAMELYON16_CLAM/pt_files"
csv_path: "/mnt/zhen_chen/AIEC/4-MIL/reference.csv"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "CAMELYON16_Ours"
feature_dim: 1024
num_levels: 3
lowest_level: 0
downsample_factor: 4
tree_dropout: [0.01, 0.05, 0.1]
visible_levels: [0, 1, 2]

# Model options
backbone: "Experts"
n_experts: 8
dropout: 0.5
activation: "gelu"
num_layers: 2
num_heads: 8
d_model: 512
d_state: 8
agg: 'avg'
pretrained: ""

# training options
seed: 42
batch_size: 1
epochs: 200
fold: 0

# optimizer options
opt: "adamw"
lr: 2.0e-4
scheduler: True
weight_decay: 0.05
warmup_epochs: 15
lambda_xsam: 0
lambda_xview: 1.0e+3
lambda_cls: 1
