# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "1,2,3,4"

# Paths
train_path: "/mnt/zhen_chen/mDATA_train.pkl"
test_path: "/mnt/zhen_chen/mDATA_test.pkl"
csv_path: "/mnt/zhen_chen/AIEC/4-MIL/reference.csv"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "CAMELYON16_DTFD"
feature_dim: 1024

# Model options
backbone: "Transformer"
dropout: 0.5
activation: "gelu"
num_layers: 2
num_heads: 4
d_model: 512
d_state: 8
agg: 'avg'
pretrained: ""

# training options
seed: 42
batch_size: 1
epochs: 200
fold: 0

# optimizer options
opt: "adamw"
lr: 2.0e-4
scheduler: True
weight_decay: 0.05
warmup_epochs: 15
